#!/usr/bin/env bash
set -Eeuo pipefail

dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
#-------------------------------------------------------------------------------
"$dir/project" sh -c 'test ! -f build || ./build'

"$dir/project" sh -c 'test ! -f docker-compose.yml || docker compose up -d'

"$dir/../docker/ps-await-healthy"

docker ps
