#!/usr/bin/env bash
set -Eeuo pipefail

tag=${1}
dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
#-------------------------------------------------------------------------------
"$dir/project" git checkout testing
"$dir/project" git pull

if ! git diff --quiet ; then
    git add -A
    git commit -m "update"
fi

"$dir/project-tag-create" "$tag"
"$dir/project" git push

"$dir/project" git checkout stable
"$dir/project" git pull
"$dir/project" git merge "$tag"
"$dir/project" git push

"$dir/project" sh -c 'test ! -f .dockerrepo || docker-deploy'
