#!/usr/bin/env bash
set -Eeuo pipefail

dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
#-------------------------------------------------------------------------------
"$dir/project" git tag -l 2>/dev/null | sort -Vu | tail
