#!/usr/bin/env bash
set -Eeuo pipefail

cmd=$1
shift 1
opts=("$@")
dir=$(dirname "$(realpath "${BASH_SOURCE[0]}")")

case $cmd in
    build)
    if (( ${#opts[@]} )); then
        exec "$dir/docker/build-compose" "${opts[@]}"
    else
        exec "$dir/docker/build-compose"
    fi
        ;;
    deploy)
    if (( ${#opts[@]} )); then
        exec "$dir/docker/build-tags" "${opts[@]}"
    else
        exec "$dir/docker/build-tags"
    fi
        ;;
    upgrade)
    if (( ${#opts[@]} )); then
        exec "$dir/docker/upgrade" "${opts[@]}"
    else
        exec "$dir/docker/upgrade"
    fi
        ;;
    *)
    if (( ${#opts[@]} )); then
        exec docker compose "$cmd" "${opts[@]}"
    else
        exec docker compose "$cmd"
    fi
        ;;
esac
