#!/usr/bin/env bash
set -Eeuo pipefail

cmd=$1
shift 1
opts=("$@")
dir=$(dirname "$(realpath "${BASH_SOURCE[0]}")")
args=()
if (( ${#opts[@]} )); then args+=("${opts[@]}"); fi

case $cmd in
    build)
        exec "$dir/docker/build-compose" "${args[@]}"
        ;;
    deploy)
        exec "$dir/docker/build-tags" "${args[@]}"
        ;;
    upgrade)
        exec "$dir/docker/upgrade" "${args[@]}"
        ;;
    *)
        exec docker compose "$cmd" "${args[@]}"
        ;;
esac
