#!/usr/bin/env bash
set -Eeuo pipefail
shopt -s inherit_errexit failglob

cmd=$1
shift 1
opts=("$@")
dir=$(dirname "$(realpath "${BASH_SOURCE[0]}")")

case $cmd in
    build)
        exec "$dir/docker/build-compose" "${opts[@]}"
        ;;
    deploy)
        exec "$dir/docker/build-tags" "${opts[@]}"
        ;;
    upgrade)
        exec "$dir/docker/upgrade" "${opts[@]}"
        ;;
    *)
        exec docker compose "$cmd" "${opts[@]}"
        ;;
esac
