#!/usr/bin/env bash
set -Eeuo pipefail

svc=$1
shift 1
cmd=${1:-}
shift 1 || true
opts1=()
opts2=()
opts3=("$@")

case $svc in
    mysql)
        opts1=(-u mysql -w /var/lib/mysql)
        cmd=${cmd:-mysql}
        opts2=(-u user -D user --password=user)
        ;;
    postgres)
        opts1=(-u postgres -w /var/lib/postgresql)
        cmd=${cmd:-psql}
        ;;
    redis)
        opts1=(-u redis)
        cmd=${cmd:-redis-cli}
        ;;
    *)
        cmd=${cmd:-bash}
        ;;
esac

args=()
if (( ${#opts1[@]} )); then args+=("${opts1[@]}"); fi
args+=("$svc" "$cmd")
if (( ${#opts2[@]} )); then args+=("${opts2[@]}"); fi
if (( ${#opts3[@]} )); then args+=("${opts3[@]}"); fi

exec docker compose exec "${args[@]}"
