#!/usr/bin/env bash
set -Eeuo pipefail

svc=$1
shift 1
cmd=${1:-}
shift 1 || true
opts1=()
opts2=()
opts3=("$@")

case $svc in
    mysql)
        opts1=(-u mysql -w /var/lib/mysql)
        cmd=${cmd:-mysql}
        opts2=(-u root --password=root)
        ;;
    postgres)
        opts1=(-u postgres -w /var/lib/postgresql)
        cmd=${cmd:-psql}
        ;;
    redis)
        opts1=(-u redis)
        cmd=${cmd:-redis-cli}
        ;;
    *)
        cmd=${cmd:-bash}
        ;;
esac

exec docker compose run "${opts1[@]}" "$svc" "$cmd" "${opts2[@]}" "${opts3[@]}"
