#!/usr/bin/env bash
set -Eeuo pipefail

mapfile -t pods < <(
    kubectl get pods \
        --field-selector status.phase==Running \
        --no-headers \
        --output custom-columns=NAME:.metadata.name)

for pod in "${pods[@]}" ; do
    tmp_s=$(kubectl exec "$pod" -- du -d0 -h /tmp)
    echo "$pod $tmp_s"
done
