#!/usr/bin/env bash
set -Eeuo pipefail
#-------------------------------------------------------------------------------
rsync \
    -e "env SSH_AUTH_SOCK=$SSH_AUTH_SOCK ssh" \
    --rsync-path="sudo rsync" \
    "$@"
