#!/usr/bin/env bash
set -Eeuo pipefail

mkdir -p ~/.local/share/bash-completion/completions

ln -sf ~/lib-shell-common/docker/bash-completion ~/.local/share/bash-completion/completions/dc
ln -sf ~/lib-shell-common/docker/bash-completion ~/.local/share/bash-completion/completions/dce
ln -sf ~/lib-shell-common/docker/bash-completion ~/.local/share/bash-completion/completions/dcr
