#!/usr/bin/env bash

source /usr/share/bash-completion/completions/docker

_dc() {
    local previous_extglob_setting=$(shopt -p extglob)
    shopt -s extglob
    local cur prev words cword
    _get_comp_words_by_ref -n : cur prev words cword
    words=(dc compose "${words[@]:1}")
    _docker_compose
    eval "$previous_extglob_setting"
}

_dce() {
    local previous_extglob_setting=$(shopt -p extglob)
    shopt -s extglob
    local cur prev words cword
    _get_comp_words_by_ref -n : cur prev words cword
    words=(dce compose exec "${words[@]:1}")
    _docker_compose
    eval "$previous_extglob_setting"
}

_dcr() {
    local previous_extglob_setting=$(shopt -p extglob)
    shopt -s extglob
    local cur prev words cword
    _get_comp_words_by_ref -n : cur prev words cword
    words=(dcr compose run "${words[@]:1}")
    _docker_compose
    eval "$previous_extglob_setting"
}

complete -F _dc  dc
complete -F _dce dce
complete -F _dcr dcr
