#!/usr/bin/env bash
set -Eeuo pipefail

dir=$(dirname "$(realpath "${BASH_SOURCE[0]}")")

mkdir -p ~/.local/share/bash-completion/completions

ln -sf "$dir/bash-completion" ~/.local/share/bash-completion/completions/dc
ln -sf "$dir/bash-completion" ~/.local/share/bash-completion/completions/dce
ln -sf "$dir/bash-completion" ~/.local/share/bash-completion/completions/dcr
