#!/usr/bin/env bash
set -Eeuo pipefail

docker build \
  --target dev \
  --cache-from "$REPO:$TAG.dev" \
  --cache-from "$REPO:latest.dev" \
  --build-arg BUILDKIT_INLINE_CACHE=1 \
  --build-arg GIT_DESCRIBE="$(git describe)" \
  -t "$REPO:$TAG.dev" .

docker push "$REPO:$TAG.dev"
