#!/usr/bin/env bash
set -Eeuo pipefail

opts=("$@")

if (( ${#opts[@]} )); then
    docker compose "${opts[@]}" build \
        --build-arg GIT_DESCRIBE="$(git describe)"
else
    docker compose build \
        --build-arg GIT_DESCRIBE="$(git describe)"
fi