#!/usr/bin/env bash
set -Eeuo pipefail

source "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/init"

docker build \
  --target prd \
  --cache-from "$REPO:$TAG.dev" \
  --cache-from "$REPO:$TAG.prd" \
  --cache-from "$REPO:latest.dev" \
  --cache-from "$REPO:latest.prd" \
  --build-arg BUILDKIT_INLINE_CACHE=1 \
  --build-arg GIT_DESCRIBE="$(git describe)" \
  -t "$REPO:$TAG.prd" .

docker push "$REPO:$TAG.prd"
