#!/usr/bin/env bash
set -Eeuo pipefail

export DOCKER_BUILDKIT=1

branch=$(git rev-parse --abbrev-ref HEAD)
release=$(git describe --abbrev=0)
repo=$(<.dockerrepo)
version=$(git describe)

tags=("$branch")

if [ "$version" == "$release" ]; then
    r=$release
    r_=""
    
    while true; do
        tags+=("$r")
        r=${r%.*}
        
        if [ "$r" == "$r_" ]; then
            break
        else
            r_=$r
        fi
    done
fi

args=()

for tag in "${tags[@]}"; do
    args+=("-t")
    args+=("$repo:$tag")
done

docker build \
    --build-arg GIT_DESCRIBE="$(git describe)" \
    "${args[@]}" .

for tag in "${tags[@]}"; do
    docker push "$repo:$tag"
done

echo
echo "version: $version"
echo "repo:    $repo"
echo "tags:    ${tags[*]}"
