#!/usr/bin/env bash
set -Eeuo pipefail

cmd=${1:-}
shift 1 || true
opts=("$@")

if [ -z "$cmd" ]; then
    cmd=redis-cli
fi
#-------------------------------------------------------------------------------
docker compose exec \
    -u redis \
    redis "$cmd" "${opts[@]}"
