#!/usr/bin/env bash
set -Eeuo pipefail

cmd=${1:-}
shift 1 || true
opts=("$@")

if [ -z "$cmd" ]; then
    cmd=psql
fi
#-------------------------------------------------------------------------------
docker compose exec \
    -u postgres \
    -w /var/lib/postgresql \
    postgres "$cmd" "${opts[@]}"
