#!/usr/bin/env bash
set -Eeuo pipefail

docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

export DOCKER_BUILDKIT=1

REPO=$(<.dockerrepo)
TAG=$(git rev-parse --abbrev-ref HEAD | tr '/' '-')
export REPO TAG
