#!/usr/bin/env bash
set -Eeuo pipefail

while test ! -z "$(docker ps -f health=starting -f health=unhealthy -q)"; do
    cNames=()
    while IFS= read -r name; do
        cNames+=("$name")
    done < <(docker ps \
        -f health=starting -f health=unhealthy --format '{{.Names}}')

    printf "\r\033[2KAwaiting %ss %s" "${SECONDS}" "${cNames[*]}"
    
    sleep 1
done

echo
