#!/usr/bin/env bash
set -Eeuo pipefail
#-------------------------------------------------------------------------------
while test ! -z "$(docker ps -f health=starting -f health=unhealthy -q)"; do
    mapfile -t cNames < <(docker ps \
        -f health=starting -f health=unhealthy --format '{{.Names}}')
    
    echo -ne "\r\e[2KAwaiting ${cNames[*]}"
    
    sleep 1
done

echo
