#!/usr/bin/env bash
set -Eeuo pipefail

dockerfile=${1:-Dockerfile}

grep -E '^# FROMFREEZE (.*)$' "$dockerfile" | while read -r line; do
    data=${line#"# FROMFREEZE "}
    repo=${data%:*}
    tag=${data#*:}
    
    echo "Pulling $repo:$tag"
    docker pull "$repo:$tag"
    
    echo "Digesting $repo:$tag"
    digest=$(docker inspect --format='{{index .RepoDigests 0}}' "$repo:$tag" | cut -d '@' -f2)
    echo "  => $digest"
    
    sed -i -E "s|^FROM ${repo}[:@]\S+(.*)$|FROM $repo@$digest\1|g" "$dockerfile"
done
