#!/usr/bin/env bash
set -Eeuo pipefail

dir=$(dirname "$(realpath "${BASH_SOURCE[0]}")")

function echo_line() {
    printf %"$(tput cols)"s | tr " " "="
}
#-------------------------------------------------------------------------------
"$dir/each-without-project" sh -c '
    make -q build ; test $? -eq 2 || make build'
#-------------------------------------------------------------------------------
echo_line
echo -e "START\n"

"$dir/each" sh -c '
    test ! -f docker-compose.yml || docker compose up -d'
#-------------------------------------------------------------------------------
echo_line
echo -e "AWAIT\n"

"$dir/../docker/ps-await-healthy"

docker ps
