#!/usr/bin/env bash
set -Eeuo pipefail
shopt -s inherit_errexit failglob

dir=$(dirname "$(realpath "${BASH_SOURCE[0]}")")

function echo_line() {
    printf %"$(tput cols)"s | tr " " "-"
}

"$dir/each-without-project" "$@"

echo_line
echo -e "$(basename "$PWD")\n" >&2
"$@"
