#!/usr/bin/env bash
set -Eeuo pipefail

f_projects=.projects

function echo_line() {
    printf %"$(tput cols)"s | tr " " "-"
}

if [ -f "$f_projects" ] ; then
    while read -r module ; do
        pushd "$module" >/dev/null
        
        echo_line
        echo -e "$module\n" >&2
        "$@"
        
        popd >/dev/null
    done < "$f_projects"
fi
