#!/usr/bin/env bash
set -Eeuo pipefail

tag=${1}
dir=$(dirname "$(realpath "${BASH_SOURCE[0]}")")

"$dir/each" git checkout testing

"$dir/each" git pull --no-recurse-submodules

if ! git diff --quiet ; then
    git add -A
    git commit -m "update"
fi

"$dir/tag-create" "$tag"

"$dir/each" git push

"$dir/each" git checkout stable

"$dir/each" git pull --no-recurse-submodules

"$dir/each" git merge "$tag"

"$dir/each" git push

"$dir/each" sh -c 'test ! -f deploy || ./deploy'
