#!/usr/bin/env bash
set -Eeuo pipefail

tag=${1}
dir=$(dirname "$(realpath "${BASH_SOURCE[0]}")")

"$dir/each" git checkout latest

"$dir/each" git pull --no-recurse-submodules

if ! git diff --quiet ; then
    git add -A
    git commit -m "update"
fi

"$dir/tag-create" "$tag"

"$dir/each" git push

"$dir/each" sh -c '
    make -q deploy ; test $? -eq 2 || make deploy'
