#!/usr/bin/env bash
set -Eeuo pipefail

dir=$(dirname "$(realpath "${BASH_SOURCE[0]}")")

"$dir/each" sh -c '
    test ! -f docker-compose.yml || docker compose up -d'

"$dir/../docker/ps-await-healthy"

docker ps
