#!/usr/bin/env bash
set -Eeuo pipefail

tag=${1}
dir=$(realpath "$(dirname "${BASH_SOURCE[0]}")")
#-------------------------------------------------------------------------------
"$dir/each" git tag -l 2>/dev/null | sort -Vu | grep "$tag" && exit 1

"$dir/each" git tag -s "$tag" -m "$tag"
"$dir/each" git push origin "$tag"
