#!/usr/bin/env bash
set -Eeuo pipefail

dir=$(realpath "$(dirname "${BASH_SOURCE[0]}")")
#-------------------------------------------------------------------------------
"$dir/each" git tag -l 2>/dev/null | sort -Vu | tail
