#!/usr/bin/env bash
set -Eeuo pipefail

dir=$(dirname "$(realpath "${BASH_SOURCE[0]}")")

function echo_line() {
    printf %"$(tput cols)"s | tr " " "="
}
#-------------------------------------------------------------------------------
echo_line
echo -e "REPO PULL\n"

"$dir/../git/recursive" pull --no-recurse-submodules
#-------------------------------------------------------------------------------
echo_line
echo -e "UPGRADE\n"

"$dir/each-without-project" sh -c '
    make -q upgrade ; test $? -eq 2 || make upgrade'
#-------------------------------------------------------------------------------
echo_line
echo -e "UPGRADE START\n"

"$dir/start"
#-------------------------------------------------------------------------------
echo_line
echo -e "UPGRADE STOP\n"

"$dir/stop"
#-------------------------------------------------------------------------------
echo_line
echo -e "REBUILD\n"

"$dir/each-without-project" sh -c '
    make -q build ; test $? -eq 2 || make build'
#-------------------------------------------------------------------------------
echo_line
echo -e "REBUILD START\n"

"$dir/start"
#-------------------------------------------------------------------------------
echo_line
echo -e "REBUILD STOP\n"

"$dir/stop"
#-------------------------------------------------------------------------------
echo_line
echo -e "COMPLETED\n"
