#!/usr/bin/env bash
set -Eeuo pipefail

self=$(realpath "${BASH_SOURCE[0]}")
dir=$(dirname "$self")

function upgrade() {
    "$dir/../git/recursive" pull --no-recurse-submodules
    
    "$dir/each" truncate -c -s0 \
        Gemfile.lock \
        cabal.config \
        cabal.project.freeze \
        yarn.lock
    
    "$dir/each" sh -c "
        test ! -f upgrade ||
        test \"$(realpath upgrade)\" = \"$self\" ||
        ./upgrade
    "
}

function freeze() {
    "$dir/each" sh -c 'test ! -f freeze || ./freeze'
}

function test-all() {
    "$dir/each" sh -c 'test ! -f test-all || ./test-all'
}

function stop() {
    "$dir/each" sh -c 'test ! -f docker-compose.yml || docker compose stop'
}

upgrade
"$dir/build"
freeze
test-all
stop
"$dir/build"
stop
