#!/usr/bin/env bash
set -Eeuo pipefail

dir=$(dirname "$(realpath "${BASH_SOURCE[0]}")")

function echo_line() {
    printf %"$(tput cols)"s | tr " " "="
}
#-------------------------------------------------------------------------------
echo_line
echo -e "PULL\n"

"$dir/pull"
#-------------------------------------------------------------------------------
echo_line
echo -e "UPGRADE\n"

"$dir/each-without-project" "$dir/make-upgrade"
#-------------------------------------------------------------------------------
echo_line
echo -e "REBUILD\n"

"$dir/each-without-project" "$dir/make-build"
#-------------------------------------------------------------------------------
echo_line
echo -e "START\n"

"$dir/start"
#-------------------------------------------------------------------------------
echo_line
echo -e "STOP\n"

"$dir/stop"
#-------------------------------------------------------------------------------
echo_line
echo -e "COMPLETED\n"
