#!/usr/bin/env bash
set -Eeuo pipefail

f_ansible_template=$1
f_kubernetes_configmap=$2

regex_kubernetes_configmap=$(
    grep '|node_cpu' "$f_kubernetes_configmap" |
    awk '{print $3}' |
    cut -d'"' -f2)

grep '^      regex: .*|node_cpu_seconds_total|.*' "$f_ansible_template" |
    awk '{ print $2}' |
    sed 's/|/\n/g' |
    grep -Ev "($regex_kubernetes_configmap)" |
    tr '\n' '|' |
    sed 's/.$//'

echo
